#!/usr/bin/env bash

if [[ -z $P4CLIENT ]]; then 
    eval "$(p4env -print)"
fi 

if [[ -f "$1" ]]; then 
    nvrmmod
    chmod +x "$1" &>/dev/null || true 
    failed=
    if [[ $2 == "-i" ]]; then 
        sudo env IGNORE_CC_MISMATCH=1 IGNORE_MISSING_MODULE_SYMVERS=1 "$1" || failed=1
    else
        sudo env IGNORE_CC_MISMATCH=1 IGNORE_MISSING_MODULE_SYMVERS=1 "$1" -s --no-kernel-module-source --skip-module-load || failed=1
    fi 
    if [[ $failed -eq 1 ]]; 
        cat '/var/log/nvidia-installer.log'
    else 
        echo "$1" >~/.driver 
        echo "Generated ~/.driver"
        if [[ -f /tmp/nvrmmod && $(cat /tmp/nvrmmod) == "multi-user" ]]; then 
            sudo systemctl set-default graphical
            sudo rm -f /tmp/nvrmmod 
        fi 
    fi 
elif [[ $1 == "redo" ]]; then 
    if [[ ! -f $(cat ~/.driver) ]]; then
        echo "Invalid path in ~/.driver"
        exit 1
    fi 
    $(realpath $(dirname $0)) $(cat ~/.driver $2)
elif [[ ! -z $1 ]]; then  
    if sudo test ! -d /root/nvt; then 
        sudo /mnt/linuxqa/nvt.sh sync
    fi 
    sudo env NVTEST_INSTALLER_REUSE_INSTALL=False /mnt/linuxqa/nvt.sh drivers "$@" 2>/tmp/std2 | tee /tmp/std1 
    cat /tmp/std2
    driver=$(cat /tmp/std2 | grep 'NVTEST_DRIVER=' | awk '{print $2}' | awk -F'=' '{print $2}')
    if [[ ! -z $driver ]]; then 
        if [[ $driver == "http"* ]]; then 
            mkdir -p $HOME/drivers
            local_driver=$HOME/drivers/$(basename "$driver")
            wget --no-check-certificate -O $local_driver $driver || exit 1
            echo "$local_driver" > ~/.driver 
            echo "Generated ~/.driver"
        elif [[ -f $driver ]]; then 
            echo "$driver" > ~/.driver 
            echo "Generated ~/.driver"
        fi 
    fi 
else 
    find /wanliz_sw_linux/dev /wanliz_sw_linux/rel -type d -name '_out' -exec find '{}' -type f -name 'NVIDIA-Linux*.run' \;
2>/dev/null
fi 