#!/usr/bin/env bash

if [[ -z $P4CLIENT ]]; then 
    eval "$(p4env -print)"
fi 

branch=r580
target=.
config=develop 
arch=$(uname -m | sed 's/x86_64/amd64/g')
jobs=$(nproc)
nvmake_args_from_cmdline=
print=
regen=

while [[ ! -z $1 ]]; do 
    case $1 in 
        bugfix_main|r580) branch=$1 ;;
        sweep|drivers|opengl|inspect-gpu-page-tables|microbench) target=$1 ;;
        debug|release|develop) config=$1 ;;
        amd64|x64|x86_64) arch=amd64 ;;
        aarch64|arm64) arch=aarch64 ;;
        -j1) jobs=1 ;;
        -print) print=1 ;;
        -regen) regen=1 ;;
        *) nvmake_args_from_cmdline+=" $1" ;;
    esac
    shift 
done 

[[ $config == "release" ]] && trace_code=0 || trace_code=1

unixbuild_args="--unshare-namespaces \
    --tools $P4ROOT/tools \
    --devrel $P4ROOT/devrel/SDK/inc/GL "
nvmake_args="NV_COLOR_OUTPUT=1 \
    NV_GUARDWORD= \
    NV_COMPRESS_THREADS=$(nproc) \
    NV_FAST_PACKAGE_COMPRESSION=zstd \
    NV_USE_FRAME_POINTER=1 \
    NV_UNIX_LTO_ENABLED= \
    NV_LTCG= \
    NV_UNIX_CHECK_DEBUG_INFO=0 \
    NV_MANGLE_SYMBOLS= \
    NV_TRACE_CODE=$trace_code \
    linux $config $arch -j$jobs"

if [[ $branch == "bugfix_main" ]]; then 
    workdir="$P4ROOT/dev/gpu_drv/bugfix_main"
elif [[ $branch == "r580" ]]; then
    workdir="$P4ROOT/rel/gpu_drv/r580/r580_00"
else
    echo "Invalid branch \"$branch\""
    exit 1
fi 

if [[ $target == "drivers" ]]; then 
    nvmake_args+=" drivers dist"
elif [[ $target == "opengl" ]]; then 
    workdir+="/drivers/OpenGL"
elif [[ $target == "inspect-gpu-page-tables" ]]; then 
    unixbuild_args+=" --source $workdir --envvar NV_SOURCE=$workdir --extra $P4ROOT/pvt/aritger"
    workdir="$P4ROOT/pvt/aritger/apps/inspect-gpu-page-tables"
elif [[ $target == "microbench" ]]; then 
    workdir="$P4ROOT/apps/gpu/drivers/vulkan/microbench"
elif [[ $target == "sweep" ]]; then 
    cd $workdir &&
    $P4ROOT/tools/linux/unix-build/unix-build $unixbuild_args nvmake sweep 
    exit 0
else
    if [[ -f makefile.nvmk ]]; then 
        workdir="$(pwd)"
    else
        echo "Invalid target: \"$target\""
        exit 1
    fi 
fi 

if [[ $print -eq 1 ]]; then 
    echo "$P4ROOT/tools/linux/unix-build/unix-build $unixbuild_args nvmake $nvmake_args $nvmake_args_from_cmdline"
    echo 
fi 

echo "$branch => $target => linux $arch $config"
if [[ ! -z $nvmake_args_from_cmdline ]]; then 
    echo "nvmake args from cmdline: $nvmake_args_from_cmdline"
fi 
read -p "Press [Enter] to continue: "

cd $workdir || exit 1
if [[ $regen == 1 ]]; then 
    time $P4ROOT/tools/linux/unix-build/unix-build $unixbuild_args nvmake @generate
fi 
time $P4ROOT/tools/linux/unix-build/unix-build $unixbuild_args nvmake $nvmake_args $nvmake_args_from_cmdline 2>/tmp/std2

if [[ ${PIPESTATUS[0]} -ne 0 ]]; then 
    cat /tmp/std2 | grep -i 'error:\|: \*\*\*'
fi 

pwd 
