#!/usr/bin/env bash

if [[ -z $P4CLIENT ]]; then 
    eval "$(p4env -print)"
fi 

his_changelist=$1
if [[ -z $his_changelist ]]; then 
    echo "Missing cmdline arguments:"
    echo "    \$1 - changelist to checkout"
    exit 1
fi 

if [[ $2 == to && ! -z $3 ]]; then 
    local_changelist=$3 
else 
    read -p "Local changelist (optional): " local_changelist 
fi 

if [[ -z $local_changelist ]]; then 
    his_desc=$(p4 describe -s $his_changelist | head -3 | tail -1 | sed 's/^[[:space:]]*//')
    echo "$his_desc"
    read -p "New description (optional): " desc
    if [[ -z $desc ]]; then 
        desc="$his_desc"
    fi 

    local_changelist=$(p4 change -i <<EOF | awk '{print $2}'
Change: new

Client: $P4CLIENT
User: $P4USER
Status: new

Description:
    $desc
EOF
    )
    if [[ $? != 0 || -z $local_changelist ]]; then
        echo "Failed to create changelist" 
        exit 1
    fi
else
    read -p "Revert all files in $local_changelist? [Y/n]: " choice_revert
    if [[ -z $choice_revert || $choice_revert == y ]]; then 
        p4 revert -c $local_changelist //... || exit 1
        echo "Revert all local changes ... [OK]"
        echo 
    fi 
fi 

p4 unshelve -s $his_changelist -c $local_changelist || exit 1
echo "Unshelve to local files .. [OK]"
echo 

p4 resolve || true 
echo "Changes saved into $local_changelist"