#!/usr/bin/env bash

export P4PORT="p4proxy-sc.nvidia.com:2006"
export P4USER="wanliz"
export P4CLIENT="wanliz_sw_linux"
export P4ROOT="/wanliz_sw_linux"
export P4IGNORE="$HOME/.p4ignore"

if [[ ! -f ~/.p4ignore ]]; then 
    cat >~/.p4ignore <<EOF
_out
.git
.vscode
.cursorignore
.clangd
.p4config
.p4ignore
compile-commands.json
*.code-workspace
EOF
fi 

if [[ $1 == "-s" ]]; then 
    exit 0
else
    exec bash -i
fi 