#!/usr/bin/env bash

if [[ -z $DISPLAY ]]; then 
    export DISPLAY=:0
    echo "Fall back to DISPLAY=$DISPLAY"
fi 

if [[ ! -d ~/viewperf2020v3 ]]; then
    rsync -ah --info=progress2 /mnt/linuxqa/wanliz/viewperf2020v3.$(uname -m)/ ~/viewperf2020v3 || exit 1
fi 

declare -A viewset_names=(
    ["catia"]="catia-06"
    ["creo"]="creo-03"
    ["energy"]="energy-03"
    ["maya"]="maya-06"
    ["medical"]="medical-03"
    ["snx"]="snx-04"
    ["sw"]="solidworks-07"
)

read -p "Viewset (optional): " viewsets
read -p "Subtest (optional): " subtest 
read -p "Samples (optional): " samples 

if [[ -z $viewsets ]]; then 
    viewsets="catia creo energy maya medical snx sw"
    rm -rf $HOME/viewperf2020v3/results
    mkdir -p $HOME/viewperf2020v3/results
fi 
if [[ -z $samples ]]; then 
    samples=1
fi 

cd $HOME/viewperf2020v3 || exit 1

results="${viewsets// /,}"$'\n'
for i in $(seq $samples); do 
    for viewset in $viewsets; do 
        $HOME/viewperf2020v3/viewperf/bin/viewperf viewsets/$viewset/config/$viewset.xml $subtest -resolution 3840x2160 && {
            results_xml=$HOME/viewperf2020v3/results/${viewset_names[$viewset]}/results.xml
            composite_score=$(cat $results_xml | grep "Composite" | awk -F'"' '{print $2}')
            results+="$composite_score,"
            cat $results_xml 
        }  
    done 
    [[ $results == *, ]] && results=${results%,}$'\n'
    echo "$results" | column -s, -t
    echo 
done 