#!/usr/bin/env bash

if [[ -z $DISPLAY ]]; then 
    export DISPLAY=:0
    echo "Fallback to DISPLAY=$DISPLAY"
fi 

if [[ ! -d ~/viewperf2020v3 ]]; then
    rsync -ah --info=progress2 /mnt/linuxqa/wanliz/viewperf2020v3.$(uname -m)/ ~/viewperf2020v3 || exit 1
fi 

declare -A viewset_names=(
    ["catia"]="catia-06"
    ["creo"]="creo-03"
    ["energy"]="energy-03"
    ["maya"]="maya-06"
    ["medical"]="medical-03"
    ["snx"]="snx-04"
    ["sw"]="solidworks-07"
)

while [[ ! -z $1 ]]; do 
    case $1 in 
        -memalloc5) 
            export __GL_DEBUG_MASK=MEMALLOC
            export __GL_DEBUG_LEVEL=5
        ;;
        *) echo "Unknown option: $1" ;;
    esac
    shift 
done 

read -p "Viewset (optional): " viewsets
read -p "Subtest (optional): " subtest 
read -p "Samples (optional): " samples 

if [[ -z $viewsets ]]; then 
    viewsets="catia creo energy maya medical snx sw"
    rm -rf $HOME/viewperf2020v3/results
    mkdir -p $HOME/viewperf2020v3/results
fi 
if [[ -z $samples ]]; then 
    samples=1
fi 

cd $HOME/viewperf2020v3 || exit 1

results="${viewsets// /,}"$'\n'
read -r -a parts <<< "$viewsets"
column_count=${#parts[@]}
for i in $(seq $samples); do 
    column_index=1
    for viewset in $viewsets; do 
        $HOME/viewperf2020v3/viewperf/bin/viewperf viewsets/$viewset/config/$viewset.xml $subtest -resolution 3840x2160 && {
            results_xml=$HOME/viewperf2020v3/results/${viewset_names[$viewset]}/results.xml
            composite_score=$(cat $results_xml | grep "Composite" | awk -F'"' '{print $2}')
        } || {
            composite_score=0
        }
        if [[ $column_index -eq $column_count ]]; then 
            results+="$composite_score"$'\n'
        else
            results+="$composite_score,"
        fi 
        cat $results_xml 
        echo "$results" | column -s, -t
        echo 
    done 
    ((column_index++))
done 